window.ESCOLHA_CERTA_PRODUCTS = [
    {
    searchId: "Aula-F75-Branco",
    id: "65C9VX-QHHH",
    title: "Teclado mecânico Aula F75 75% - Glacial Blue ",
    category: "Tecnologia",
    badge: "Teclado Mecanico Gamer",
    price: 380.90,
    oldPrice: 499.9,
    date: "2026-06-02",
    store: "Mercado Livre",
    image: "src/aula_f75/aula_f75_branco.jpg",
    link: "https://meli.la/1P6Zb4v",
    excerpt:
      "Teclado mecânico AULA F75 Glacial Blue com layout compacto de 75% e 80 teclas. Conta com conexão Bluetooth, 2.4GHz e USB-C, ideal para jogos e produtividade. Possui RGB personalizável, switches hot-swap e digitação silenciosa com 5 camadas internas. Bateria de 4000mAh, baixa latência e keycaps PBT para mais durabilidade e desempenho.",
  },
  {
    searchId: "Aula-F75-Preto",
    id: "65C9VX-9UQ2",
    title: "Teclado mecânico Aula F75 75% - Leobog Axys Graywood v3 ",
    category: "Tecnologia",
    badge: "Teclado Mecanico Gamer",
    price: 355.90,
    oldPrice: 399.9,
    date: "2026-06-02",
    store: "Mercado Livre",
    image: "src/aula_f75/aula_f75_preto.jpg",
    link: "https://meli.la/1b5iMmN",
    excerpt:
      "Teclado mecânico AULA F75 Leobog Axys Graywood v3 com layout compacto de 75% e 80 teclas. Conta com conexão Bluetooth, 2.4GHz e USB-C, ideal para jogos e produtividade. Possui RGB personalizável, switches hot-swap e digitação silenciosa com 5 camadas internas. Bateria de 4000mAh, baixa latência e keycaps PBT para mais durabilidade e desempenho.",
  },
  {
    searchId: "Fifine-SC3-Preto",
    id: "65C9VX-E1LB",
    title: "Fifine Gaming Mixer Ampligame SC3 - Preto",
    category: "Tecnologia",
    badge: "Áudio para criadores",
    price: 299.9,
    oldPrice: 419.9,
    date: "2026-05-30",
    store: "Mercado Livre",
    image: "src/fifine_sc3/fifinesc3_01.jpg",
    link: "https://meli.la/3227WYY",
    excerpt:
      "O Fifine SC3 é uma interface de áudio compacta, ideal para melhorar a qualidade de som em jogos, lives, chamadas e gravações. Possui conexão USB-C, alimentação via USB e compatibilidade com setups simples de computador. Conta com 4 canais, equalizador, alimentação fantasma e efeitos como reverb, delay, pitch e chorus. Com entradas USB, XLR e P2/Jack, oferece praticidade e flexibilidade para diferentes acessórios de áudio.",
    highlights: [
      "Conexões USB-C, XLR e P2/Jack",
      "Efeitos de voz com reverb, delay, pitch e chorus",
      "Alimentação fantasma para microfones compatíveis",
    ],
    specs: [
      { label: "Canais", value: "4 canais" },
      { label: "Conexão", value: "USB-C, XLR e P2/Jack" },
      { label: "Uso indicado", value: "Lives, jogos, chamadas e gravações" },
      { label: "Recursos", value: "EQ, efeitos e phantom power" },
    ],
  },
  {
    searchId: "Fifine-SC3-Branco",
    id: "65C9VX-988E",
    title: "Fifine Gaming Mixer Ampligame SC3 - Branco",
    category: "Tecnologia",
    badge: "Áudio para criadores",
    price: 345.9,
    oldPrice: 419.9,
    date: "2026-05-30",
    store: "Mercado Livre",
    image: "src/fifine_sc3/fifinesc3_02.jpg",
    link: "https://meli.la/2HbnniT",
    excerpt:
      "O Fifine SC3 é uma interface de áudio compacta, ideal para melhorar a qualidade de som em jogos, lives, chamadas e gravações. Possui conexão USB-C, alimentação via USB e compatibilidade com setups simples de computador. Conta com 4 canais, equalizador, alimentação fantasma e efeitos como reverb, delay, pitch e chorus. Com entradas USB, XLR e P2/Jack, oferece praticidade e flexibilidade para diferentes acessórios de áudio.",
    highlights: [
      "Conexões USB-C, XLR e P2/Jack",
      "Efeitos de voz com reverb, delay, pitch e chorus",
      "Alimentação fantasma para microfones compatíveis",
    ],
    specs: [
      { label: "Canais", value: "4 canais" },
      { label: "Conexão", value: "USB-C, XLR e P2/Jack" },
      { label: "Uso indicado", value: "Lives, jogos, chamadas e gravações" },
      { label: "Recursos", value: "EQ, efeitos e phantom power" },
    ],
  },

];
